# Generated by Django 4.0.1 on 2022-01-06 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_alter_section_section_add_student_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='company',
        ),
        migrations.AddField(
            model_name='section',
            name='exam_associated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.examination'),
        ),
    ]
