# Generated by Django 4.0.1 on 2022-01-08 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_remove_response_table_associated_exam_add_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='response_table',
            name='exam_associated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.examination'),
        ),
    ]
