# Generated by Django 4.0.1 on 2022-01-13 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_alter_student_result_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='exam_end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 14, 1, 24, 28, 22193), null=True),
        ),
        migrations.AlterField(
            model_name='examination',
            name='exam_start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 14, 1, 24, 28, 22193), null=True),
        ),
    ]
