# Generated by Django 4.0.1 on 2022-01-05 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_user_type_adminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_assign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.adminuser'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_joining',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
